# 01 — Data Understanding

## Bank Marketing Dataset

**Goal:** Understand the dataset structure before any analysis.

**Dataset:** 45,211 clients from a Portuguese bank contacted by phone.

**Target:** `y` (yes/no) — Did the client subscribe to a term deposit?

**Author:** Fatima Azzahra
**Date:** 2026-10-09

In [1]:
# Core libraries 
import pandas as pd 
import numpy as np 
import math as m 

# Visualization 
import matplotlib.pyplot as plt 
import seaborn as sns 

# Display options 
pd.set_option('display.max_columns', None) 
sns.set_style('whitegrid')  

print("Libraries imported successfully!")

Libraries imported successfully!

In [2]:
#Load Data 
df = pd.read_csv('../data/bank-full.csv', sep=';')
print("Data loaded successfully!")

Data loaded successfully!

**Group A: Dataset Structure**

In [3]:
#Number of rows and columns 
print('Rows:', df.shape[0])
print('Columns:' ,df.shape[1])

Rows: 45211
Columns: 17

In [4]:
#Name of the  the 17 columns of the dataset 
list(df.columns)

['age',
 'job',
 'marital',
 'education',
 'default',
 'balance',
 'housing',
 'loan',
 'contact',
 'day',
 'month',
 'duration',
 'campaign',
 'pdays',
 'previous',
 'poutcome',
 'y']

In [5]:
#the first 5 rows 
df.head(5)

,age,job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome,y
0,58,management,married,tertiary,no,2143,yes,no,unknown,5,may,261,1,-1,0,unknown,no
1,44,technician,single,secondary,no,29,yes,no,unknown,5,may,151,1,-1,0,unknown,no
2,33,entrepreneur,married,secondary,no,2,yes,yes,unknown,5,may,76,1,-1,0,unknown,no
3,47,blue-collar,married,unknown,no,1506,yes,no,unknown,5,may,92,1,-1,0,unknown,no
4,33,unknown,single,unknown,no,1,no,no,unknown,5,may,198,1,-1,0,unknown,no

In [6]:
# 10 random rows look like 
df.sample(10)

,age,job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome,y
11173,36,management,single,tertiary,no,391,no,no,unknown,18,jun,443,1,-1,0,unknown,no
38283,28,admin.,single,secondary,no,7,yes,no,cellular,15,may,87,1,-1,0,unknown,no
15672,30,management,married,tertiary,no,692,yes,yes,cellular,21,jul,336,4,-1,0,unknown,no
13246,34,admin.,married,tertiary,no,434,no,no,cellular,8,jul,165,3,-1,0,unknown,no
24560,41,unemployed,married,primary,no,557,yes,no,cellular,17,nov,158,1,173,1,failure,no
8588,26,blue-collar,single,secondary,no,17891,yes,no,unknown,3,jun,239,1,-1,0,unknown,no
12517,32,blue-collar,single,secondary,no,-255,no,yes,unknown,2,jul,957,3,-1,0,unknown,no
23477,42,technician,married,secondary,no,29,no,no,cellular,28,aug,53,11,-1,0,unknown,no
30274,32,admin.,single,secondary,no,642,yes,no,cellular,5,feb,52,1,253,2,failure,no
923,30,services,single,tertiary,no,542,yes,no,unknown,7,may,435,2,-1,0,unknown,no

In [7]:
#the types of each column 
df.dtypes

age          int64
job            str
marital        str
education      str
default        str
balance      int64
housing        str
loan           str
contact        str
day          int64
month          str
duration     int64
campaign     int64
pdays        int64
previous     int64
poutcome       str
y              str
dtype: object

In [8]:
#the types of each column  
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 45211 entries, 0 to 45210
Data columns (total 17 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   age        45211 non-null  int64
 1   job        45211 non-null  str
 2   marital    45211 non-null  str
 3   education  45211 non-null  str
 4   default    45211 non-null  str
 5   balance    45211 non-null  int64
 6   housing    45211 non-null  str
 7   loan       45211 non-null  str
 8   contact    45211 non-null  str
 9   day        45211 non-null  int64
 10  month      45211 non-null  str
 11  duration   45211 non-null  int64
 12  campaign   45211 non-null  int64
 13  pdays      45211 non-null  int64
 14  previous   45211 non-null  int64
 15  poutcome   45211 non-null  str
 16  y          45211 non-null  str
dtypes: int64(7), str(10)
memory usage: 5.9 MB

In [9]:
# explicit missing values (NaN)
df.isnull().sum()

age          0
job          0
marital      0
education    0
default      0
balance      0
housing      0
loan         0
contact      0
day          0
month        0
duration     0
campaign     0
pdays        0
previous     0
poutcome     0
y            0
dtype: int64

**Group B: Descriptive Statistics**

In [10]:
#the statistics of the numeric columns (mean, min, max, quartiles ,std) 

df.describe()

,age,balance,day,duration,campaign,pdays,previous
count,45211.000000,45211.000000,45211.000000,45211.000000,45211.000000,45211.000000,45211.000000
mean,40.936210,1362.272058,15.806419,258.163080,2.763841,40.197828,0.580323
std,10.618762,3044.765829,8.322476,257.527812,3.098021,100.128746,2.303441
min,18.000000,-8019.000000,1.000000,0.000000,1.000000,-1.000000,0.000000
25%,33.000000,72.000000,8.000000,103.000000,1.000000,-1.000000,0.000000
50%,39.000000,448.000000,16.000000,180.000000,2.000000,-1.000000,0.000000
75%,48.000000,1428.000000,21.000000,319.000000,3.000000,-1.000000,0.000000
max,95.000000,102127.000000,31.000000,4918.000000,63.000000,871.000000,275.000000

In [11]:
# the statistics of the categorical columns (unique values, most frequent value) 
df.describe(include ='object')

C:\Users\DELL\AppData\Local\Temp\ipykernel_13864\1398984560.py:2: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  df.describe(include ='object')

,job,marital,education,default,housing,loan,contact,month,poutcome,y
count,45211,45211,45211,45211,45211,45211,45211,45211,45211,45211
unique,12,3,4,2,2,2,3,12,4,2
top,blue-collar,married,secondary,no,yes,no,cellular,may,unknown,no
freq,9732,27214,23202,44396,25130,37967,29285,13766,36959,39922

In [12]:
#  the minimum and maximum age of the clients 
print('min age :', df['age'].min())
print('max age :', df['age'].max())

min age : 18
max age : 95

In [13]:
# The minimum and maximum bank balance , Number of negative balances? 
print('min balance :',df['balance'].min()) 
print('max balance :',df['balance'].max()) 
print('Number of negative balances :', (df['balance'] < 0).sum())

min balance : -8019
max balance : 102127
Number of negative balances : 3766

In [14]:
# the maximum value of campaign,  Are there any clients who were called many times? 
print('max calls :', df['campaign'].max())
print('Number of clients called more than 5 times :', (df['campaign'] > 5).sum())

max calls : 63
Number of clients called more than 5 times : 4355

**Group C: The Target Variable y**

In [19]:
# How many clients said yes and how many said no? 
df['y'].value_counts()

y
no     39922
yes     5289
Name: count, dtype: int64

In [25]:
#  the percentage of clients who subscribed 
df['y'].value_counts(normalize=True)*100

y
no     88.30152
yes    11.69848
Name: proportion, dtype: float64

# Is the dataset balanced or imbalanced? Why does it matter? 
**Answer:** No, the dataset is highly **imbalanced**. 
About 88.3% of clients said "no", and only 11.7% said "yes".

**Why is it important ?**
If we train a model on this dataset, a "lazy" model that always predicts "no" would have an 88% accuracy. However, it would be completely useless for the bank because it would never identify the clients who say "yes". 

We will need to handle this imbalance later by using specific metrics (like Recall and F1-score) instead of just Accuracy, and by applying techniques like class weighting.

**Group D: Data Quality**

In [29]:
# Duplicates in the dataset
df.duplicated().sum()

np.int64(0)

In [33]:
# Which columns contain the value "unknown" and  How many times per column? 
df[df=='unknown'].count()

age              0
job            288
marital          0
education     1857
default          0
balance          0
housing          0
loan             0
contact      13020
day              0
month            0
duration         0
campaign         0
pdays            0
previous         0
poutcome     36959
y                0
dtype: int64

In [ ]:
# What does pdays = -1 mean? How many clients have this value?
# `pdays` represents the number of days since the client was last contacted from a previous campaign. 
# The value `-1` is not a real number of days; it is a  meaning that the client has never been contacted before.
(df['pdays'] == -1).sum()

np.int64(36954)

**Group E: Synthesis** 
### Data Understanding Summary

**Dataset Overview:** 
The dataset contains 45,211 clients and 17 variables (7 numerical, 10 categorical). There are no duplicate rows and no explicit missing values (NaN). 

**Target Variable (`y`):** 
The dataset is highly **imbalanced**: 88.3% of clients said "no" and only 11.7% said "yes". This will be a major challenge for Machine Learning.

**Data Quality Issues:** 
We found hidden missing values represented as `"unknown"`, especially in `poutcome` (81.7%) and `contact` (28.8%). We also found that `pdays = -1` means the client was never contacted before. 

**Next Steps:** 
We need to find a strategy to handle the `"unknown"` values in Phase 2 (Cleaning), and we must be careful with the class imbalance when building our prediction model.